# https://github.com/chdsbd/kodiak
version = 1

[approve]
auto_approve_usernames = ["dependabot"]

[merge]
method = "squash"
delete_branch_on_merge = true

[merge.message]
title = "pull_request_title"
include_pr_number = true
body = "pull_request_body"